-- APAGANDO O BANCO DE DADOS
DROP DATABASE IF EXISTS DBEXERCICIO10;

-- CRIANDO O BANCO DE DADOS 
CREATE DATABASE DBEXERCICIO10;

-- CONECTANDO AO BANCO
USE DBEXERCICIO10;

-- CRIANDO A TABELA 
CREATE TABLE FEED (
 IDFEED INT NOT NULL AUTO_INCREMENT
, USUARIO VARCHAR(120) NOT NULL
, DT_PUBLICACAO DATETIME NOT NULL
, TEXTO VARCHAR(200)
, TAG VARCHAR(100) NOT NULL
, URL_IMAGEM VARCHAR(200) NOT NULL
, PRIMARY KEY (IDFEED)
);