-- VERIFICANDO SE O BANCO DE DADOS EXISTE 
DROP DATABASE IF EXISTS DBEXERCICIO07;

-- CRIANDO O BANCO DE DADOS	
CREATE DATABASE DBEXERCICIO07;

-- CONECTANDO AO BANCO DE DADOS	
USE DBEXERCICIO07;

-- CRIANDO AS TABELAS 
CREATE TABLE HOSPEDE (
IDHOSPEDE INT NOT NULL AUTO_INCREMENT
, NOME VARCHAR(120) NOT NULL
, CPF CHAR(11)
, EMAIL VARCHAR(120)
, DT_CHECKIN DATE
, DT_CHECKOUT DATE 
, ASSINATURA CHAR(1)
, DT_CADASTRO DATE 
, PRIMARY KEY (IDHOSPEDE) 
);