-- APAGANDO O BANCO DE DADOS
DROP DATABASE IF EXISTS DBEXERCICIO11;

-- CRIANDO O BANCO DE DADOS 
CREATE DATABASE DBEXERCICIO11;

-- CONECTANDO AO BANCO
USE DBEXERCICIO11;

-- CRIANDO A TABELA 
CREATE TABLE INSCRICAO (
IDINSCRICAO INT NOT NULL auto_increment
, NOME VARCHAR(120) NOT NULL
, DT_NASCIMENTO DATE NOT NULL
, TELEFONE VARCHAR(17) NOT NULL
, PARENTESCO_CONTATO1 VARCHAR(17) NOT NULL
, TELEFONE_CONTATO1 VARCHAR(17) NOT NULL
, TELEFONE_CONTATO2 VARCHAR(17)
, EMAIL VARCHAR(120) NOT NULL
, ENDERECO VARCHAR(120) NOT NULL
, CIDADE VARCHAR(50) NOT NULL
, ESTADO CHAR(2) NOT NULL
, CURSO VARCHAR(100) NOT NULL
, ASSINATURA CHAR(1) NOT NULL
, DT_CADASTRO DATE NOT NULL
, NOME_CONTATO1 VARCHAR(120) NOT NULL
, NOME_CONTATO2 VARCHAR(120)
, PARENTESCO_CONTATO2 VARCHAR(17)
, PRIMARY KEY (IDINSCRICAO)
);