-- APAGANDO O BANCO DE DADOS
DROP DATABASE IF EXISTS DBEXERCICIO08;

-- CRIANDO O BANCO DE DADOS 
CREATE DATABASE DBEXERCICIO08;

-- CONECTANDO AO BANCO
USE DBEXERCICIO08;

-- CRIANDO A TABELA 
CREATE TABLE CONTA (
IDCONTA INT NOT NULL AUTO_INCREMENT
, NOME VARCHAR(120) NOT NULL
, EMAIL VARCHAR(120) NOT NULL
, SENHA VARCHAR(50) NOT NULL
, CELULAR int
, ACEIT CHAR(1) NOT NULL
, CURSO VARCHAR(100) 
, primary key (IDCONTA)
);