-- APAGANDO O BANCO DE DADOS
DROP DATABASE IF EXISTS DBEXERCICIO09;

-- CRIANDO O BANCO DE DADOS 
CREATE DATABASE DBEXERCICIO09;

-- CONECTANDO AO BANCO
USE DBEXERCICIO09;

-- CRIANDO A TABELA 
CREATE TABLE CONTA (
IDCONTA INT NOT NULL AUTO_INCREMENT
, NOME VARCHAR(120) NOT NULL 
, EMAIL VARCHAR(120) NOT NULL
, SENHA VARCHAR(50) NOT NULL
, CPF CHAR(11) NOT NULL
, ENDERECO VARCHAR(120) NOT NULL
, VINCULO_FACEBOOK VARCHAR(200)
, VINCULO_GOOGLE VARCHAR(200)
, PRIMARY KEY (IDCONTA)
);