-- APAGANDO O BANCO DE DADOS
DROP DATABASE IF EXISTS DBEXERCICIO12;

-- CRIANDO O BANCO DE DADOS 
CREATE DATABASE DBEXERCICIO12;

-- CONECTANDO AO BANCO
USE DBEXERCICIO12;

-- CRIANDO A TABELA 
CREATE TABLE LOCATARIO (
IDLOCATARIO INT NOT NULL auto_increment
, NOME VARCHAR(120) NOT NULL
, TELEFONE VARCHAR(17) NOT NULL
, ASSINATURA CHAR(1) NOT NULL
, DT_CADASTRO DATE NOT NULL
, CPF CHAR(11) NOT NULL
, ENDERECO VARCHAR(120) NOT NULL
, DT_INICIO_CONTRATO DATE NOT NULL
, DT_FIM_CONTRATO DATE NOT NULL
, VALOR_ALGUEL DECIMAL(10,2) NOT NULL
, NOME_DEPENDENTE VARCHAR(120) NOT NULL
, DT_NASCIMENTO_DEPENDENTE date
, NOME_DEPENDENTE2 VARCHAR(120) 
, DT_NASCIMENTO_DEPENDENTE2 DATE
, PRIMARY KEY (IDLOCATARIO)
);